### ISSUE TITLE
[feat] DOCKER_REPO env var 

### ISSUE THREAD

**Issue by matzew** [boson-project/functions#10]
**Is your feature request related to a problem? Please describe.**

The doc says:

> Provide a container registry location where you have permission to create images. This will typically be, for example, a personal Docker Hub or Quay.io account. You will be prompted for this value.

and on the shell, I see:

```
➜  myfunc kn faas build
Building image: 
A registry for Function images is required. For example, 'docker.io/tigerteam'.

Registry for Function images: docker.io/matzew
```

## Proposal

Perhaps introduce an envar for the user to set?  The UX on the function seems a bit fishy, that I enter it _after_ the build :shrug: 

E.g. in Knative we have `KO_DOCKER_REPO`... perhaps something like that  ?  or some cfg file ?

**Comment by zroubalik** [comment]
There's one already, `FAAS_REGISTRY`, serving exactly this purpose, we should improve the docs though.

**Comment by matzew** [comment]
> serving exactly this purpose, we should improve the docs though.

@zroubalik wanna do a "doc bug" ?
